// The wallets Nura Swap presents by name, with self-hosted official vectors
// (public/wallets, generated by scripts/build-wallets.mjs).
//
// Why a roster at all when EIP-6963 announces what is installed: a visitor with
// NOTHING installed used to get one dead sentence. Showing the roster tells them
// which wallets work here and where to get one - and a wallet that IS installed
// still arrives by announcement and is matched to its brand by rdns.
//
// The roster is a display aid, never a gate: any announced wallet connects,
// listed here or not, using the icon it announces. Hard-coded brand lists are
// exactly what EIP-6963 exists to end.

export interface WalletBrand
{
    /** EIP-6963 rdns - the identity a wallet announces itself under. */
    rdns: string;
    label: string;
    /**
     * The wallet's OWN vector, or null when we do not ship one. Null draws a
     * neutral glyph: lending one brand's logo to another is a misrepresentation,
     * the same reason an imported token cannot borrow a coin mark.
     */
    icon: string | null;
    /** Where to get it, for a visitor who has none. */
    install: string;
}

/**
 * The one exception to "any announced wallet connects": wallets this site does
 * not offer, by rdns. A wallet named here is not listed, not restored from a
 * saved session, and not reachable through the sheet at all - dropping it from
 * discovery rather than from the markup is what keeps those three answers the
 * same one.
 *
 * Keep the list short. Every entry costs a visitor who has that wallet and now
 * has nowhere to click, so it is a deliberate product choice each time, not
 * housekeeping.
 */
export const HIDDEN_WALLETS: ReadonlySet<string> = new Set([
    'com.coinbase.wallet',
    // OKX ships under both spellings depending on the build. Naming one and not
    // the other hides the wallet on some machines and leaves it on others, and
    // the failure is invisible from here - so name both.
    'com.okex.wallet',
    'com.okx.wallet'
]);

export function isHiddenWallet(rdns: string): boolean
{
    return HIDDEN_WALLETS.has(rdns);
}

export const WALLET_BRANDS: WalletBrand[] = [
    {
        rdns: 'io.metamask',
        label: 'MetaMask',
        icon: '/wallets/metamask.svg',
        install: 'https://metamask.io/download/'
    },
    {
        rdns: 'com.trustwallet.app',
        label: 'Trust Wallet',
        icon: '/wallets/trust.svg',
        install: 'https://trustwallet.com/browser-extension'
    }
];

export function brandFor(rdns: string): WalletBrand | undefined
{
    return WALLET_BRANDS.find((brand) => brand.rdns === rdns);
}
