// The wallets Nura Swap presents by name, with self-hosted official vectors
// (public/wallets, generated by scripts/build-wallets.mjs).
//
// Why a roster at all when EIP-6963 announces what is installed: a visitor with
// NOTHING installed used to get one dead sentence. Showing the roster tells them
// which wallets work here and where to get one - and a wallet that IS installed
// still arrives by announcement and is matched to its brand by rdns.
//
// The roster is a display aid, never a gate: any announced wallet connects,
// listed here or not, using the icon it announces. Hard-coded brand lists are
// exactly what EIP-6963 exists to end.

export interface WalletBrand
{
    /** EIP-6963 rdns - the identity a wallet announces itself under. */
    rdns: string;
    label: string;
    /**
     * The wallet's OWN vector, or null when we do not ship one. Null draws a
     * neutral glyph: lending one brand's logo to another is a misrepresentation,
     * the same reason an imported token cannot borrow a coin mark.
     */
    icon: string | null;
    /** Where to get it, for a visitor who has none. */
    install: string;
}

export const WALLET_BRANDS: WalletBrand[] = [
    {
        rdns: 'io.metamask',
        label: 'MetaMask',
        icon: '/wallets/metamask.svg',
        install: 'https://metamask.io/download/'
    },
    {
        rdns: 'com.trustwallet.app',
        label: 'Trust Wallet',
        icon: '/wallets/trust.svg',
        install: 'https://trustwallet.com/browser-extension'
    }
];

export function brandFor(rdns: string): WalletBrand | undefined
{
    return WALLET_BRANDS.find((brand) => brand.rdns === rdns);
}
